#pragma once
#include "graphics/gui_interface.hpp"  
#include <QMainWindow>
#include <QFileDialog>
#include <QMessageBox>
#include <QPixmap>


/**
 * @file mainwindow.hpp
 * @brief Main application window for the steganography GUI.
 *
 * Provides slots to load images, switch between Embed/Extract modes, and
 * to process embedding or extraction with PVD or LSB-DCT methods.
 */
#pragma once

QT_BEGIN_NAMESPACE
namespace Ui { class MainWindow; }
QT_END_NAMESPACE

class QTextEdit;



/**
 * @class MainWindow
 * @brief The main application window for the steganography GUI.
 *
 * Provides controls to load an image, choose between embedding and extracting modes,
 * select the method (PVD or LSB-DCT), enter a message or number of bits, and display
 * the original and resulting images or extracted text.
 */
class MainWindow : public QMainWindow
{
    Q_OBJECT

public:


    /**
     * @brief Construct the main window.
     * @param parent The parent widget, if any (defaults to nullptr).
     *
     * Sets up the UI, connects button and combo-box signals to slots,
     * and initializes the controls to match the default mode.
     */
    explicit MainWindow(QWidget* parent = nullptr);

    /**
     * @brief Destructor for the main window.
     *
     * Cleans up the UI object.
     */
    ~MainWindow();

private slots:


    /**
     * @brief Slot called when the \"Load Image\" button is clicked.
     *
     * Opens a file dialog to let the user pick an image. If a file is selected,
     * loads and displays it in the \"Original\" image label.
     */
    void onLoadImageClicked();


    /**
     * @brief Slot called when the mode combo box changes (Embed/Extract).
     * @param index The new combo-box index (unused).
     *
     * Enables or disables the message input and bit-count spinbox based on
     * the selected mode, and updates the process button’s text.
     */
    void onModeChanged(int index);

     /**
     * @brief Slot called when the \"Embed/Extract\" button is clicked.
     *
     * If no image is loaded, shows an error. Otherwise, performs embedding
     * or extraction using the selected method (PVD or LSB-DCT) and displays
     * the result (image or extracted text).
     */
    void onProcessClicked();

private:
    Ui::MainWindow* ui; /**< The UI form generated by Qt Designer. */
    QString loadedImagePath; /**< Path of the currently loaded image. */
};